/**
 * Config class has constant variables to ensure proper input and output
 * messages for the program.
 * 
 * DO NOT EDIT THIS FILE, OR HAND IN. 
 * WE WILL USE OUR OWN CONFIG FILE, SO BE SURE THAT YOUR PROGRAM USES
 * THESE VALUES VIA THEIR NAMES.
 * 
 * @see Train
 * @see TrainHubMain
 * @see TrainGenerator
 */
public class Config {

	//** Use by TrainGenerator Class **//
	
	/** the minimum number of CargoCar in a generated train */
	public static final int MIN_CART_NUM = 50;	
	
	/** the maximum number of CargoCar in a generated train */
	public static final int MAX_CART_NUM = 100;	
	
	/** the minimum weight of CargoCar in a generated train */
	public static final int MIN_WEIGHT = 2000;	
	
	/** the maximum weight of CargoCar in a generated train */
	public static final int MAX_WEIGHT = 10000;	
	
	// Lists for Cargo names and Destinations
	/** Possible types of cargo carried */
	public static final String[] CARGO_ARRAY = 
				{"Coal", "Crude Oil", "Ethanol", "Steel", "Lumber", "Stone"};

	/** Possible destinations */
	public static final String[] DEST_ARRAY = 
				{"Chicago", "Milwaukee", "Green Bay", "Lacrosse", "Eau Claire", 
								"Prairie du Chien", "Oconomowoc"};
	
	//** Used by Train Class **//
	
	// FOR EXAMPLE
	// ([dest])->[cargo]:[weight]->[cargo]:[weight]->...
	
	/** Character before destination name in train output string */
	public static final String ENGINE_START = "(";

	/** Character after destination name in train output */
	public static final String ENGINE_END = ")";
	
	/** Characters before between cargo cars in train output string */
	public static final String CARGO_LINK = "->";
	
	//** Used by TrainHubMain Class **//
	
	/** Message at start of program */
	public static final String PROMPT_WELCOME_MSG = "//// Welcome to UW Train Hub ////";
	
	/** User menu between user choices */
	public static final String PROMPT_MENU = 
			"============== HUB CONTROL ==============\n" +
			"1. Handle a new train arrival\n" +
			"2. Remove a Cargo car from a departing Train\n" +
			"3. Get the Weight of a Cargo product from all the departing trains\n" +
			"4. Depart a Train\n" +
			"5. Depart All the Trains in Hub\n" +
			"6. Display a departing Train\n" +
			"7. Display All departing Trains in Hub\n" +
			"8. Move matching cargo from src train to dst train\n" +
			"9. Quit\n" +
			"=========================================";

	/** User input prompt for train destination */
	public static final String PROMPT_INPUT_DEST = "Enter the Destination of the Train : ";
	
	/** User input prompt for train cargo product name */
	public static final String PROMPT_INPUT_CARGO = "Enter the Cargo Name : ";
	
	/** User input prompt for train cargo weight */
	public static final String PROMPT_OUTPUT_WEIGHT = "Total weight ";

	/** User input prompt for a src train destination for moving chain */
	public static final String PROMPT_INPUT_MOVE_SRC = "Enter the Destination of the Train that has the source chain of cargo: ";
	
	/** User input prompt for a dst train destination for moving chain */
	public static final String PROMPT_INPUT_MOVE_DST = "Enter the Destination of the Train that cargo is moved to: ";

	/** Message displayed if program is not given correct arguments */
	public static final String ERROR_USAGE = "Not supported Arguments\nUsage : java TrainHubMain [-f filename1 filename2 ...]";
	
	/** Message displayed if unable to read the train input file */
	public static final String ERROR_FILE_READ = "Error occured to load a train from file : ";

	/** Message displaed if the destination does not match an expected destination */
	public static final String ERROR_DEST_NOT_FOUND = "ERROR: Train for the destination not found ";
	
	/** Message displayed if a train does not contain the requested cargo */
	public static final String ERROR_CARGO_NOT_FOUND = "ERROR: Cargo not found ";
	
	/** Message displayed if cargo not found for that destination */
	public static final String ERROR_DEST_OR_CARGO_NOT_FOUND = "ERROR: Cargo for the Train heading to the destination not found ";
	
	/** Message displayed if there is no train in the hub when user expects one */
	public static final String ERROR_NO_TRAIN_IN_HUB = "There is no train in the hub.";

	/** Message displayed if user selects an invalid menu option value */
	public static final String ERROR_WRONG_COMMAND = "Wrong command. Enter a menu number (1~9).";
	
}
